[package]
name = "server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
codec.workspace = true
data.workspace = true

json.workspace = true

[lints]
workspace = true
